name: PS3-Pro-Build-MrMouswi

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # تثبيت المكتبات مع دعم الإصدارات القديمة (Legacy)
          sudo apt-get install -y build-essential git bison flex libelf-dev libssl-dev zlib1g-dev libncurses5-dev autoconf pkg-config

      - name: Setup PS3 Public Tools
        run: |
          # سحب أدوات التوقيع
          git clone https://github.com/ifcaro/ps3publictools.git
          cd ps3publictools
          # تعديل الكود برمجياً لتجاوز مشكلة OpenSSL قبل البناء
          sed -i 's/AES_ctr128_encrypt/AES_cbc_encrypt/g' make_self.c || true
          make
          sudo make install
          cd ..

      - name: Build Application
        run: |
          # تنظيف وبناء المشروع
          make clean
          make

      - name: Upload Final PKG
        uses: actions/upload-artifact@v4
        with:
          name: PS20KGConv-Final-Build
          path: "*.pkg"
          
